name: Installation


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push


jobs:

  build-and-test:
    name: Install and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.6]

    steps:
      - uses: actions/checkout@v2
    
      - name: install-pystokes
        shell: bash -l {0}
        run: |
          python setup.py install
          make
      - name: test-pystokes
        shell: bash -l {0}
        run: |
          cd tests && python shortTests.py
