name: Notebooks

on:
    schedule:
      # 4am daily
      - cron:  '0 4 3-31/3 * *'

jobs:

  build-and-test:
    name: notebooks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pyross
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pyross
        shell: bash -l {0}
        run: |
          conda activate pyross
          make
          # make nbtest
      - name: testing-forecast
        shell: bash -l {0}
        run: |
          make nbtest -e path="examples" recursive=False
                # make nbtest
