name: notebooks

on: [push, pull_request]


jobs:
  build-and-test:
    name: check examples
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
         python-version: 3.7 
         architecture: x64
      - name: Print version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies 
        run: cd tests && python -m pip install -r test_req.txt

      - name: Install pystokes 
        run: python setup.py install 

      - name: Test example notebooks
        run: cd tests && python test_notebooks.py
