name: codecov

on: [push, pull_request]


jobs:

  build-and-test:
    name: Codecov Workflow 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
    
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.2.0
        with:
         activate-environment: pystokes
         environment-file: environment.yml
         # auto-activate-base: true
      - name: make-pystokes
        shell: bash -l {0}
        run: |
          conda activate pystokes
          make
          # make nbtest
      - name: Generate coverage report
        run: |
          pip install pytest 
          pip install pytest-cov
          pytest tests/shortTests.py --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
